name: ROS Noetic integration

on:
  pull_request:
  workflow_dispatch:

jobs:
  catkin:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-latest
    steps:
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: lslidar_ls_driver
          target-ros1-distro: noetic
          coverage-result: false
